// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuVVuZdSf7vkXbTea5KGjpVvT1KorLAA',
    appId: '1:339336500127:web:8d47e79424f0530a6e23aa',
    messagingSenderId: '339336500127',
    projectId: 'hidrocultura-d68b0',
    authDomain: 'hidrocultura-d68b0.firebaseapp.com',
    databaseURL: 'https://hidrocultura-d68b0-default-rtdb.firebaseio.com',
    storageBucket: 'hidrocultura-d68b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnE15wFJ_EXNQz1_gredVe8nX8wit_rLs',
    appId: '1:339336500127:android:31b748dcbf59701a6e23aa',
    messagingSenderId: '339336500127',
    projectId: 'hidrocultura-d68b0',
    databaseURL: 'https://hidrocultura-d68b0-default-rtdb.firebaseio.com',
    storageBucket: 'hidrocultura-d68b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6XamGpG38GtaFkB7Q1yYtp8dJ2bSvMxc',
    appId: '1:339336500127:ios:851f6783b5ccc1d96e23aa',
    messagingSenderId: '339336500127',
    projectId: 'hidrocultura-d68b0',
    databaseURL: 'https://hidrocultura-d68b0-default-rtdb.firebaseio.com',
    storageBucket: 'hidrocultura-d68b0.appspot.com',
    iosBundleId: 'com.example.flutterHidrocultura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6XamGpG38GtaFkB7Q1yYtp8dJ2bSvMxc',
    appId: '1:339336500127:ios:851f6783b5ccc1d96e23aa',
    messagingSenderId: '339336500127',
    projectId: 'hidrocultura-d68b0',
    databaseURL: 'https://hidrocultura-d68b0-default-rtdb.firebaseio.com',
    storageBucket: 'hidrocultura-d68b0.appspot.com',
    iosBundleId: 'com.example.flutterHidrocultura',
  );
}
